module.exports = {
  API_KEY: "Nope",
  SECRET_KEY: "Nope",
  SYMBOL: "SOL/USD",
  POSITION_SIZE: 0.01,
  NUM_BUY_GRID_LINES: 5,
  NUM_SELL_GRID_LINES: 5,
  GRID_SIZE: 0.25,
  CHECK_ORDERS_FREQUENCY: 1,
  CLOSED_ORDER_STATUS: "closed",
};
