API_KEY = "Nope"
SECRET_KEY = "Nope"

SYMBOL = "ETH/USD"
POSITION_SIZE = 0.001

# gridbot settings
NUM_BUY_GRID_LINES = 25
NUM_SELL_GRID_LINES = 25
GRID_SIZE = 8

CHECK_ORDERS_FREQUENCY = 1
CLOSED_ORDER_STATUS = 'closed'
